// Code generated by protoc-gen-go.
// source: HT_favorite_body.proto
// DO NOT EDIT!

/*
Package ht_favorite is a generated protocol buffer package.

It is generated from these files:
	HT_favorite_body.proto
	HT_favorite_head.proto

It has these top-level messages:
	ImageBody
	VoiceBody
	CorrectContent
	FavoriteContent
	AddReqBody
	AddRspBody
	DelReqBody
	DelRspBody
	GetReqBody
	GetRspBody
	UpdateTagReqBody
	UpdateTagRspBody
	SearchTagReqBody
	SearchTagRspBody
	SearchTextReqBody
	SearchTextRspBody
	ReqBody
	RspBody
*/
package ht_favorite

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TYPE_FAVORATE int32

const (
	TYPE_FAVORATE_TYPE_TEXT  TYPE_FAVORATE = 1
	TYPE_FAVORATE_TYPE_VOICE TYPE_FAVORATE = 2
	TYPE_FAVORATE_TYPE_CORR  TYPE_FAVORATE = 3
	TYPE_FAVORATE_TYPE_PIC   TYPE_FAVORATE = 4
	TYPE_FAVORATE_TYPE_MNT   TYPE_FAVORATE = 5
)

var TYPE_FAVORATE_name = map[int32]string{
	1: "TYPE_TEXT",
	2: "TYPE_VOICE",
	3: "TYPE_CORR",
	4: "TYPE_PIC",
	5: "TYPE_MNT",
}
var TYPE_FAVORATE_value = map[string]int32{
	"TYPE_TEXT":  1,
	"TYPE_VOICE": 2,
	"TYPE_CORR":  3,
	"TYPE_PIC":   4,
	"TYPE_MNT":   5,
}

func (x TYPE_FAVORATE) Enum() *TYPE_FAVORATE {
	p := new(TYPE_FAVORATE)
	*p = x
	return p
}
func (x TYPE_FAVORATE) String() string {
	return proto.EnumName(TYPE_FAVORATE_name, int32(x))
}
func (x *TYPE_FAVORATE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TYPE_FAVORATE_value, data, "TYPE_FAVORATE")
	if err != nil {
		return err
	}
	*x = TYPE_FAVORATE(value)
	return nil
}
func (TYPE_FAVORATE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ImageBody struct {
	ThumbUrl         []byte  `protobuf:"bytes,1,opt,name=thumb_url" json:"thumb_url,omitempty"`
	BigUrl           []byte  `protobuf:"bytes,2,opt,name=big_url" json:"big_url,omitempty"`
	Width            *uint32 `protobuf:"varint,3,opt,name=width" json:"width,omitempty"`
	Height           *uint32 `protobuf:"varint,4,opt,name=height" json:"height,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ImageBody) Reset()                    { *m = ImageBody{} }
func (m *ImageBody) String() string            { return proto.CompactTextString(m) }
func (*ImageBody) ProtoMessage()               {}
func (*ImageBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ImageBody) GetThumbUrl() []byte {
	if m != nil {
		return m.ThumbUrl
	}
	return nil
}

func (m *ImageBody) GetBigUrl() []byte {
	if m != nil {
		return m.BigUrl
	}
	return nil
}

func (m *ImageBody) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *ImageBody) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

type VoiceBody struct {
	Url              []byte  `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Duration         *uint32 `protobuf:"varint,2,opt,name=duration" json:"duration,omitempty"`
	Size             *uint32 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VoiceBody) Reset()                    { *m = VoiceBody{} }
func (m *VoiceBody) String() string            { return proto.CompactTextString(m) }
func (*VoiceBody) ProtoMessage()               {}
func (*VoiceBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VoiceBody) GetUrl() []byte {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *VoiceBody) GetDuration() uint32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *VoiceBody) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

type CorrectContent struct {
	Content          []byte `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	Correction       []byte `protobuf:"bytes,2,opt,name=correction" json:"correction,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CorrectContent) Reset()                    { *m = CorrectContent{} }
func (m *CorrectContent) String() string            { return proto.CompactTextString(m) }
func (*CorrectContent) ProtoMessage()               {}
func (*CorrectContent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CorrectContent) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *CorrectContent) GetCorrection() []byte {
	if m != nil {
		return m.Correction
	}
	return nil
}

type FavoriteContent struct {
	Obid             *string           `protobuf:"bytes,1,opt,name=obid" json:"obid,omitempty"`
	SrcUid           *uint32           `protobuf:"varint,2,opt,name=src_uid" json:"src_uid,omitempty"`
	Type             *TYPE_FAVORATE    `protobuf:"varint,3,opt,name=type,enum=ht.favorite.TYPE_FAVORATE" json:"type,omitempty"`
	Text             []byte            `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	Voice            *VoiceBody        `protobuf:"bytes,5,opt,name=voice" json:"voice,omitempty"`
	Correction       []*CorrectContent `protobuf:"bytes,6,rep,name=correction" json:"correction,omitempty"`
	Image            *ImageBody        `protobuf:"bytes,7,opt,name=image" json:"image,omitempty"`
	Mid              []byte            `protobuf:"bytes,8,opt,name=mid" json:"mid,omitempty"`
	Tags             []string          `protobuf:"bytes,9,rep,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *FavoriteContent) Reset()                    { *m = FavoriteContent{} }
func (m *FavoriteContent) String() string            { return proto.CompactTextString(m) }
func (*FavoriteContent) ProtoMessage()               {}
func (*FavoriteContent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FavoriteContent) GetObid() string {
	if m != nil && m.Obid != nil {
		return *m.Obid
	}
	return ""
}

func (m *FavoriteContent) GetSrcUid() uint32 {
	if m != nil && m.SrcUid != nil {
		return *m.SrcUid
	}
	return 0
}

func (m *FavoriteContent) GetType() TYPE_FAVORATE {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return TYPE_FAVORATE_TYPE_TEXT
}

func (m *FavoriteContent) GetText() []byte {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *FavoriteContent) GetVoice() *VoiceBody {
	if m != nil {
		return m.Voice
	}
	return nil
}

func (m *FavoriteContent) GetCorrection() []*CorrectContent {
	if m != nil {
		return m.Correction
	}
	return nil
}

func (m *FavoriteContent) GetImage() *ImageBody {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *FavoriteContent) GetMid() []byte {
	if m != nil {
		return m.Mid
	}
	return nil
}

func (m *FavoriteContent) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AddReqBody struct {
	Content          *FavoriteContent `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *AddReqBody) Reset()                    { *m = AddReqBody{} }
func (m *AddReqBody) String() string            { return proto.CompactTextString(m) }
func (*AddReqBody) ProtoMessage()               {}
func (*AddReqBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddReqBody) GetContent() *FavoriteContent {
	if m != nil {
		return m.Content
	}
	return nil
}

type AddRspBody struct {
	Obid             []byte  `protobuf:"bytes,1,opt,name=obid" json:"obid,omitempty"`
	LastTs           *uint32 `protobuf:"varint,2,opt,name=last_ts" json:"last_ts,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddRspBody) Reset()                    { *m = AddRspBody{} }
func (m *AddRspBody) String() string            { return proto.CompactTextString(m) }
func (*AddRspBody) ProtoMessage()               {}
func (*AddRspBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AddRspBody) GetObid() []byte {
	if m != nil {
		return m.Obid
	}
	return nil
}

func (m *AddRspBody) GetLastTs() uint32 {
	if m != nil && m.LastTs != nil {
		return *m.LastTs
	}
	return 0
}

type DelReqBody struct {
	Obid             []byte `protobuf:"bytes,1,opt,name=obid" json:"obid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DelReqBody) Reset()                    { *m = DelReqBody{} }
func (m *DelReqBody) String() string            { return proto.CompactTextString(m) }
func (*DelReqBody) ProtoMessage()               {}
func (*DelReqBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DelReqBody) GetObid() []byte {
	if m != nil {
		return m.Obid
	}
	return nil
}

type DelRspBody struct {
	LastTs           *uint32 `protobuf:"varint,1,opt,name=last_ts" json:"last_ts,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DelRspBody) Reset()                    { *m = DelRspBody{} }
func (m *DelRspBody) String() string            { return proto.CompactTextString(m) }
func (*DelRspBody) ProtoMessage()               {}
func (*DelRspBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DelRspBody) GetLastTs() uint32 {
	if m != nil && m.LastTs != nil {
		return *m.LastTs
	}
	return 0
}

type GetReqBody struct {
	Index            *string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	LastTs           *uint32 `protobuf:"varint,2,opt,name=last_ts" json:"last_ts,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetReqBody) Reset()                    { *m = GetReqBody{} }
func (m *GetReqBody) String() string            { return proto.CompactTextString(m) }
func (*GetReqBody) ProtoMessage()               {}
func (*GetReqBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetReqBody) GetIndex() string {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return ""
}

func (m *GetReqBody) GetLastTs() uint32 {
	if m != nil && m.LastTs != nil {
		return *m.LastTs
	}
	return 0
}

type GetRspBody struct {
	ContentList      []*FavoriteContent `protobuf:"bytes,1,rep,name=content_list" json:"content_list,omitempty"`
	Index            *string            `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
	More             *uint32            `protobuf:"varint,3,opt,name=more" json:"more,omitempty"`
	LastTs           *uint32            `protobuf:"varint,4,opt,name=last_ts" json:"last_ts,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GetRspBody) Reset()                    { *m = GetRspBody{} }
func (m *GetRspBody) String() string            { return proto.CompactTextString(m) }
func (*GetRspBody) ProtoMessage()               {}
func (*GetRspBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetRspBody) GetContentList() []*FavoriteContent {
	if m != nil {
		return m.ContentList
	}
	return nil
}

func (m *GetRspBody) GetIndex() string {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return ""
}

func (m *GetRspBody) GetMore() uint32 {
	if m != nil && m.More != nil {
		return *m.More
	}
	return 0
}

func (m *GetRspBody) GetLastTs() uint32 {
	if m != nil && m.LastTs != nil {
		return *m.LastTs
	}
	return 0
}

type UpdateTagReqBody struct {
	Obid             []byte   `protobuf:"bytes,1,opt,name=obid" json:"obid,omitempty"`
	Tags             []string `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UpdateTagReqBody) Reset()                    { *m = UpdateTagReqBody{} }
func (m *UpdateTagReqBody) String() string            { return proto.CompactTextString(m) }
func (*UpdateTagReqBody) ProtoMessage()               {}
func (*UpdateTagReqBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UpdateTagReqBody) GetObid() []byte {
	if m != nil {
		return m.Obid
	}
	return nil
}

func (m *UpdateTagReqBody) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type UpdateTagRspBody struct {
	LastTs           *uint32 `protobuf:"varint,1,opt,name=last_ts" json:"last_ts,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateTagRspBody) Reset()                    { *m = UpdateTagRspBody{} }
func (m *UpdateTagRspBody) String() string            { return proto.CompactTextString(m) }
func (*UpdateTagRspBody) ProtoMessage()               {}
func (*UpdateTagRspBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UpdateTagRspBody) GetLastTs() uint32 {
	if m != nil && m.LastTs != nil {
		return *m.LastTs
	}
	return 0
}

type SearchTagReqBody struct {
	Tag              *string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	LastTs           *uint32 `protobuf:"varint,2,opt,name=last_ts" json:"last_ts,omitempty"`
	Index            *string `protobuf:"bytes,3,opt,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SearchTagReqBody) Reset()                    { *m = SearchTagReqBody{} }
func (m *SearchTagReqBody) String() string            { return proto.CompactTextString(m) }
func (*SearchTagReqBody) ProtoMessage()               {}
func (*SearchTagReqBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SearchTagReqBody) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *SearchTagReqBody) GetLastTs() uint32 {
	if m != nil && m.LastTs != nil {
		return *m.LastTs
	}
	return 0
}

func (m *SearchTagReqBody) GetIndex() string {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return ""
}

type SearchTagRspBody struct {
	ContentList      []*FavoriteContent `protobuf:"bytes,1,rep,name=content_list" json:"content_list,omitempty"`
	Index            *string            `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
	More             *uint32            `protobuf:"varint,3,opt,name=more" json:"more,omitempty"`
	LastTs           *uint32            `protobuf:"varint,4,opt,name=last_ts" json:"last_ts,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SearchTagRspBody) Reset()                    { *m = SearchTagRspBody{} }
func (m *SearchTagRspBody) String() string            { return proto.CompactTextString(m) }
func (*SearchTagRspBody) ProtoMessage()               {}
func (*SearchTagRspBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SearchTagRspBody) GetContentList() []*FavoriteContent {
	if m != nil {
		return m.ContentList
	}
	return nil
}

func (m *SearchTagRspBody) GetIndex() string {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return ""
}

func (m *SearchTagRspBody) GetMore() uint32 {
	if m != nil && m.More != nil {
		return *m.More
	}
	return 0
}

func (m *SearchTagRspBody) GetLastTs() uint32 {
	if m != nil && m.LastTs != nil {
		return *m.LastTs
	}
	return 0
}

type SearchTextReqBody struct {
	Text             *string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	LastTs           *uint32 `protobuf:"varint,2,opt,name=last_ts" json:"last_ts,omitempty"`
	Index            *string `protobuf:"bytes,3,opt,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SearchTextReqBody) Reset()                    { *m = SearchTextReqBody{} }
func (m *SearchTextReqBody) String() string            { return proto.CompactTextString(m) }
func (*SearchTextReqBody) ProtoMessage()               {}
func (*SearchTextReqBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SearchTextReqBody) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *SearchTextReqBody) GetLastTs() uint32 {
	if m != nil && m.LastTs != nil {
		return *m.LastTs
	}
	return 0
}

func (m *SearchTextReqBody) GetIndex() string {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return ""
}

type SearchTextRspBody struct {
	ContentList      []*FavoriteContent `protobuf:"bytes,1,rep,name=content_list" json:"content_list,omitempty"`
	Index            *string            `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
	More             *uint32            `protobuf:"varint,3,opt,name=more" json:"more,omitempty"`
	LastTs           *uint32            `protobuf:"varint,4,opt,name=last_ts" json:"last_ts,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SearchTextRspBody) Reset()                    { *m = SearchTextRspBody{} }
func (m *SearchTextRspBody) String() string            { return proto.CompactTextString(m) }
func (*SearchTextRspBody) ProtoMessage()               {}
func (*SearchTextRspBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SearchTextRspBody) GetContentList() []*FavoriteContent {
	if m != nil {
		return m.ContentList
	}
	return nil
}

func (m *SearchTextRspBody) GetIndex() string {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return ""
}

func (m *SearchTextRspBody) GetMore() uint32 {
	if m != nil && m.More != nil {
		return *m.More
	}
	return 0
}

func (m *SearchTextRspBody) GetLastTs() uint32 {
	if m != nil && m.LastTs != nil {
		return *m.LastTs
	}
	return 0
}

func init() {
	proto.RegisterType((*ImageBody)(nil), "ht.favorite.ImageBody")
	proto.RegisterType((*VoiceBody)(nil), "ht.favorite.VoiceBody")
	proto.RegisterType((*CorrectContent)(nil), "ht.favorite.CorrectContent")
	proto.RegisterType((*FavoriteContent)(nil), "ht.favorite.FavoriteContent")
	proto.RegisterType((*AddReqBody)(nil), "ht.favorite.AddReqBody")
	proto.RegisterType((*AddRspBody)(nil), "ht.favorite.AddRspBody")
	proto.RegisterType((*DelReqBody)(nil), "ht.favorite.DelReqBody")
	proto.RegisterType((*DelRspBody)(nil), "ht.favorite.DelRspBody")
	proto.RegisterType((*GetReqBody)(nil), "ht.favorite.GetReqBody")
	proto.RegisterType((*GetRspBody)(nil), "ht.favorite.GetRspBody")
	proto.RegisterType((*UpdateTagReqBody)(nil), "ht.favorite.UpdateTagReqBody")
	proto.RegisterType((*UpdateTagRspBody)(nil), "ht.favorite.UpdateTagRspBody")
	proto.RegisterType((*SearchTagReqBody)(nil), "ht.favorite.SearchTagReqBody")
	proto.RegisterType((*SearchTagRspBody)(nil), "ht.favorite.SearchTagRspBody")
	proto.RegisterType((*SearchTextReqBody)(nil), "ht.favorite.SearchTextReqBody")
	proto.RegisterType((*SearchTextRspBody)(nil), "ht.favorite.SearchTextRspBody")
	proto.RegisterEnum("ht.favorite.TYPE_FAVORATE", TYPE_FAVORATE_name, TYPE_FAVORATE_value)
}

func init() { proto.RegisterFile("HT_favorite_body.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x94, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x95, 0x38, 0x69, 0xe3, 0x89, 0x9d, 0xba, 0x3e, 0x54, 0x56, 0x01, 0xa9, 0x32, 0x42,
	0xaa, 0xf8, 0x63, 0xa4, 0x48, 0x48, 0x48, 0x1c, 0x50, 0x30, 0x29, 0xe4, 0x40, 0x53, 0x05, 0x13,
	0xd1, 0x93, 0xe5, 0xd8, 0x8b, 0xbd, 0x52, 0xe2, 0x0d, 0xf6, 0xba, 0xb4, 0x1c, 0xf9, 0xe4, 0xac,
	0x77, 0xed, 0xd8, 0x5b, 0xb5, 0x82, 0x53, 0x6f, 0x99, 0xdd, 0x99, 0xdf, 0xcc, 0x7b, 0xb3, 0x0e,
	0x1c, 0x7d, 0xf6, 0xfc, 0x1f, 0xc1, 0x15, 0xc9, 0x30, 0x45, 0xfe, 0x8a, 0x44, 0x37, 0xce, 0x36,
	0x23, 0x94, 0x98, 0xc3, 0x84, 0x3a, 0xf5, 0xb9, 0x7d, 0x0e, 0xea, 0x6c, 0x13, 0xc4, 0xe8, 0x03,
	0xbb, 0x37, 0x0f, 0x41, 0xa5, 0x49, 0xb1, 0x59, 0xf9, 0x45, 0xb6, 0xb6, 0x3a, 0x27, 0x9d, 0x53,
	0xcd, 0x3c, 0x80, 0xfd, 0x15, 0x8e, 0xf9, 0x41, 0x97, 0x1f, 0xe8, 0xd0, 0xff, 0x85, 0x23, 0x9a,
	0x58, 0x0a, 0x0b, 0x75, 0x73, 0x04, 0x7b, 0x09, 0xc2, 0x71, 0x42, 0xad, 0x5e, 0x19, 0xdb, 0x6f,
	0x41, 0x5d, 0x12, 0x1c, 0x0a, 0xde, 0x10, 0x94, 0x86, 0x64, 0xc0, 0x20, 0x2a, 0xb2, 0x80, 0x62,
	0x92, 0x72, 0x94, 0x6e, 0x6a, 0xd0, 0xcb, 0xf1, 0x6f, 0x24, 0x48, 0xf6, 0x1b, 0x18, 0xb9, 0x24,
	0xcb, 0x50, 0x48, 0x5d, 0x92, 0x52, 0x94, 0xd2, 0xb2, 0x77, 0x28, 0x7e, 0x56, 0x08, 0x13, 0x20,
	0x14, 0x29, 0x35, 0x44, 0xb3, 0xff, 0x74, 0xe1, 0xe0, 0xac, 0x52, 0x53, 0x17, 0x32, 0x30, 0x59,
	0xe1, 0x88, 0x57, 0xa9, 0x25, 0x26, 0xcf, 0x42, 0xbf, 0x60, 0x07, 0xa2, 0xef, 0x29, 0xf4, 0xe8,
	0xcd, 0x56, 0xf4, 0x1d, 0x8d, 0x8f, 0x9d, 0x96, 0x1f, 0x8e, 0x77, 0x79, 0x31, 0xf5, 0xcf, 0x26,
	0xcb, 0xf9, 0x62, 0xe2, 0x4d, 0x4b, 0x10, 0x45, 0xd7, 0x42, 0x9b, 0x66, 0x3e, 0x83, 0xfe, 0x55,
	0xa9, 0xcd, 0xea, 0xb3, 0x70, 0x38, 0x3e, 0x92, 0x0a, 0x1b, 0xd5, 0xaf, 0xa5, 0x29, 0xf7, 0x4e,
	0x14, 0x96, 0xfb, 0x48, 0xca, 0xbd, 0xa5, 0x93, 0x71, 0x71, 0xb9, 0x03, 0x6b, 0xff, 0x0e, 0x6e,
	0xb3, 0x1d, 0xe6, 0xe6, 0x86, 0x69, 0x18, 0xf0, 0x59, 0xca, 0xc9, 0x82, 0x38, 0xb7, 0x54, 0x86,
	0x57, 0xed, 0x77, 0x00, 0x93, 0x28, 0x5a, 0xa0, 0x9f, 0x3c, 0xf1, 0x95, 0xec, 0xdb, 0x70, 0xfc,
	0x58, 0x22, 0xde, 0x72, 0xcb, 0x7e, 0x21, 0x8a, 0xf3, 0x2d, 0x2f, 0x6e, 0x7b, 0xc7, 0xd7, 0xbf,
	0x0e, 0x72, 0xea, 0xd3, 0x5c, 0x78, 0x67, 0x1f, 0x03, 0x7c, 0x44, 0xeb, 0xba, 0x93, 0x94, 0x6c,
	0x3f, 0x11, 0x77, 0x15, 0xa8, 0x55, 0xda, 0xe1, 0xa5, 0x2f, 0x01, 0x3e, 0x21, 0x5a, 0x97, 0xb2,
	0x77, 0x84, 0xd3, 0x08, 0x5d, 0x37, 0x4b, 0x92, 0x1b, 0xa5, 0x22, 0xbb, 0x82, 0x8d, 0x41, 0xab,
	0x24, 0xf9, 0x6b, 0x9c, 0x97, 0xba, 0x94, 0x7f, 0xe9, 0x6a, 0x3a, 0x74, 0x79, 0x07, 0x36, 0xeb,
	0x86, 0x64, 0xd5, 0x6b, 0x6b, 0xf7, 0x13, 0x0f, 0xd7, 0x01, 0xe3, 0xdb, 0x36, 0x0a, 0x28, 0xf2,
	0x82, 0xf8, 0x4e, 0x79, 0x3b, 0xcb, 0xbb, 0xdc, 0xf2, 0xa7, 0xed, 0xfc, 0xfb, 0x24, 0xbf, 0x07,
	0xe3, 0x2b, 0x0a, 0xb2, 0x30, 0x69, 0x41, 0xd9, 0x1a, 0x19, 0xe6, 0x1e, 0xd9, 0xcd, 0xd0, 0xe5,
	0x98, 0xaa, 0x4d, 0xdb, 0x80, 0x07, 0xf3, 0x62, 0x02, 0x87, 0x55, 0x57, 0xf6, 0xf8, 0x5b, 0x66,
	0xf0, 0x6f, 0xe1, 0xff, 0x06, 0x2f, 0x24, 0xc4, 0x43, 0x4d, 0xfe, 0xfc, 0x12, 0x74, 0xf9, 0x0b,
	0xd6, 0x41, 0xe5, 0x07, 0xde, 0xf4, 0xbb, 0x67, 0x74, 0xd8, 0xdf, 0x15, 0xf0, 0x70, 0x39, 0x9f,
	0xb9, 0x53, 0xa3, 0xbb, 0xbb, 0x76, 0xe7, 0x8b, 0x85, 0xa1, 0x30, 0xfa, 0x80, 0x87, 0x17, 0x33,
	0xd7, 0xe8, 0xed, 0xa2, 0x2f, 0xe7, 0x9e, 0xd1, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x76, 0xb0,
	0x2d, 0x94, 0x4f, 0x05, 0x00, 0x00,
}
